#!/usr/bin/env sh

for file in zshrc vim vimrc gitconfig tmux.conf
do
    echo $file
    mv -f ".${file}" ".${file}.backup"
    ln -vs ".dots/${file}" ".${file}"
done

git clone https://github.com/gmarik/vundle.git .dots/vim/bundle/vundle
vim +PluginInstall +qall > /dev/null &

